### ISSUE TITLE
Remove ob-scala.el since it depends on abandoned ensime

### ISSUE THREAD

**Issue by tarsius** [hvesalai/emacs-scala-mode#155]
Because `ensime` has been abandoned, you probably should remove `ob-scala.el`.

I ran into this as part of my work on the [Emacsmirror](https://emacsmirror.net). This is one of less than a dozen missing features among the ~5000 thousand mirrored packages.

Thanks for looking into this.

**Comment by tarsius** [comment]
Friendly ping! :beer:

**Comment by tarsius** [comment]
Thanks!

**Comment by kschwarz1116** [comment]
I'm not entirely sure what would cause this, but it looks like this change did not result in a change in package number on MELPA. [This](https://melpa.org/#/scala-mode) still shows 20190929.1522. As a result, I still had `ob-scala.el` in my `elpa` directory. Uninstalling and reinstalling the package seemed to fix it, so I'm just leaving this comment here in case anyone else runs into it.

**Comment by VitalyAnkh** [comment]
Since you have [merged the two `ob-scala.el` to this package](https://github.com/hvesalai/emacs-scala-mode/issues/114), then removed the `ob-scala.el` here, how could the users use org babel for scala? Is a new `ob-scala.el` planned? :(

**Comment by hvesalai** [comment]
@VitalyAnkh we welcome all PRs. I never used ob-scala my self, so am not the best person to maintain it.
