### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by Valdaer** [hvesalai/emacs-scala-mode#158]
Hi, could you please make a new release for melpa-stable because old release requires dependency of Ensime that is now longer in development(https://ensime.github.io/) because of https://github.com/hvesalai/emacs-scala-mode/issues/155 ?

Moreover I would like to package scala-mode in Debian which once was in Debian but has been orphaned(https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766441) but I cannot package the old release without Ensime dependency(that hadn't been packaged in debian and packaging such abandoned software would be a waste of time).

**Comment by hvesalai** [comment]
Thank you for the reminder. I have now tagged v1.1.0

**Comment by Valdaer** [comment]
thanks
