### ISSUE TITLE
Don't understand rationale behind syntax hightlighting. 

### ISSUE THREAD

**Issue by smabie** [hvesalai/emacs-scala-mode#162]
![screensho](https://user-images.githubusercontent.com/1126907/89697971-bb088280-d8ec-11ea-98c2-47ef159099c0.png)

Consider the attached screenshot. Sometimes, a type is blue, other times, light green. Is this intended behavior?

**Comment by hvesalai** [comment]
Well... it is a known thing, but not fully as I would have wanted it.

But your cursor is on the `val x` line. Here `T` is not a type, it is a value (an object with `apply` method).

**Comment by hvesalai** [comment]
I.e. the thing that is not as good as I would have wanted is the type parameters, which are now Green instead of Blue. That is something I struggled with, but decided to go the way it is now to highlight the erased type.
